### ISSUE TITLE
Assertion Failure: `!is_type_untyped(type)`

### ISSUE THREAD

**Issue by salfel** [odin-lang/Odin#5820]
## Context

I just upgraded to odin version dev-2025-10 and couldn't compile my program anymore. 

* Operating System & Odin Version:
        Odin:    dev-2025-10
        OS:      NixOS 25.11 (Xantusia), Linux 6.12.52
        CPU:     AMD Ryzen 5 7640U w/ Radeon 760M Graphics
        RAM:     47573 MiB
        Backend: LLVM 18.1.8

## Expected Behavior

The program builds successfully

## Current Behavior

It can't compile

## Failure Information (for bugs)

When building the program i get the following error 
```
src/name_canonicalization.cpp(610): Assertion Failure: `!is_type_untyped(type)`
[1]    133888 illegal hardware instruction (core dumped)  odin build src -debug`
```

### Steps to Reproduce
I encountered the bug on the following [repo](https://github.com/salfel/widgets). 
When building this with the new odin compiler version, you'll get the aforementioned error.

**Comment by Kelimion** [comment]
I can replicate this, but I had to perform a lot of surgery on the repository to get this far.

Can you perhaps create a branch in the `widgets` repo with the `odin-wayland` submodule vendored into it and the global context errors for `@(init)` applied to it? That would make it easier for someone else to also replicate it. See below:

The referenced submodule commit for `odin-wayland` can't be found.
```
git submodule update --init --recursive
Cloning into 'bugs/widgets/lib/wayland'...
fatal: remote error: upload-pack: not our ref 3bcf2416858efa0eb70c53b3fe5a592af94cffda
fatal: Fetched in submodule path 'lib/wayland', but it did not contain 3bcf2416858efa0eb70c53b3fe5a592af94cffda. Direct fetching of that commit failed.
```

Then I cloned `odin-wayland` at its current commit.
```
git clone git@github.com:yasinkaraaslan/odin-wayland.git lib/wayland
Cloning into 'lib/wayland'...
remote: Enumerating objects: 146, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 146 (delta 57), reused 121 (delta 37), pack-reused 0 (from 0)
Receiving objects: 100% (146/146), 163.98 KiB | 907.00 KiB/s, done.
Resolving deltas: 100% (57/57), done.
```

So now I tried `git check`.
```
widgets $ odin check src -collection:shared=lib
widgets/lib/wayland/xdg/decoration-unstable-v1.odin(167:1) Error: @(init) procedures must be declared as "contextless"
        init_interfaces_xdg_decoration_unstable_v1 :: proc() {
        ^
        Suggestion: this can be bypassed, for the time being, with '#+feature global-context'
wayland/xdg/shell.odin(1257:1) Error: @(init) procedures must be declared as "contextless"
        init_interfaces_xdg_shell :: proc() {
        ^
        Suggestion: this can be bypassed, for the time being, with '#+feature global-context'
widgets/lib/wayland/wayland.odin(3049:1) Error: @(init) procedures must be declared as "contextless"
        init_interfaces_wayland :: proc() {
        ^
        Suggestion: this can be bypassed, for the time being, with '#+feature global-context'
```

And I fixed those by making those procedures `contextless`. No compiler error, and checking didn't fail.
```
$ odin build src -collection:shared=lib
src/name_canonicalization.cpp(610): Assertion Failure: `!is_type_untyped(type)`
Illegal instruction (core dumped)
```
Can also be replicated on Windows. Even though there's no Wayland on Windows, and Odin won't cross link, it makes debugging a lot nicer.
```
odin build src -collection:shared=lib -target:linux_amd64
W:\Odin\src\name_canonicalization.cpp(610): Assertion Failure: `!is_type_untyped(type)`
```

Edit: It's tripping on an `untyped nil`.

**Comment by salfel** [comment]
> Can you perhaps create a branch in the `widgets` repo with the `odin-wayland` submodule vendored into it and the global context errors for `@(init)` applied to it? That would make it easier for someone else to also replicate it. See below:

will do. I'm not that familiar with submodules, thought that the local commited changes would be applied in the remote. my bad.

**Comment by Kelimion** [comment]
Two more questions to narrow things down a bit.

1. You mentioned updating `Odin` to `2025-10`. Do you remember the previous version? That gives us a way to narrow down where this was introduced and what it was that evinces this bug.
2. Do you remember making any particular changes to `widgets` itself that might've triggered this bug, or does the identical code compile on <previous odin version> as per `#1`? e.g. did it work on ([fix error printing](https://github.com/salfel/widgets/commit/bb51274aa993c33462a853c52147e227fe89da03))?

**Comment by Kelimion** [comment]
Huzzah \o/
```
git clone git@github.com:salfel/widgets.git --recurse
Cloning into 'widgets'...
remote: Enumerating objects: 381, done.
remote: Counting objects: 100% (381/381), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 381 (delta 279), reused 358 (delta 256), pack-reused 0 (from 0)
Receiving objects: 100% (381/381), 577.94 KiB | 1.50 MiB/s, done.
Resolving deltas: 100% (279/279), done.
Submodule 'lib/wayland' (git@github.com:salfel/odin-wayland.git) registered for path 'lib/wayland'
Cloning into 'W:/Scratch/bugs/widgets/lib/wayland'...
remote: Enumerating objects: 190, done.
remote: Counting objects: 100% (190/190), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 190 (delta 83), reused 160 (delta 60), pack-reused 0 (from 0)
Receiving objects: 100% (190/190), 186.95 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (83/83), done.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 2), reused 2 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 2.47 KiB | 140.00 KiB/s, done.
From github.com:salfel/odin-wayland
 * branch            3bcf2416858efa0eb70c53b3fe5a592af94cffda -> FETCH_HEAD
Submodule path 'lib/wayland': checked out '3bcf2416858efa0eb70c53b3fe5a592af94cffda'
```

**Comment by salfel** [comment]
> Two more questions to narrow things down a bit.
> 
>     1. You mentioned updating `Odin` to `2025-10`. Do you remember the previous version? That gives us a way to narrow down where this was introduced and what it was that evinces this bug.
> 
>     2. Do you remember making any particular changes to `widgets` itself that might've triggered this bug, or does the identical code compile on  as per `#1`? e.g. did it work on ([fix error printing](https://github.com/salfel/widgets/commit/bb51274aa993c33462a853c52147e227fe89da03))?

the last version before the update was 2025-08.
The code still doesn't compile when on the fix error printing commit, if that's what you mean. The whole project, meaning the latest state also compiles just fine when using the 2025-08 version, with the 2025-10 i get the assertion failure error message

**Comment by Kelimion** [comment]
Using `git bisect`, I've found that the bug was most likely introduced in 4f442c60453df9e421dad8314fb76231d8bed344:
```
4f442c60453df9e421dad8314fb76231d8bed344 is the first bad commit
commit 4f442c60453df9e421dad8314fb76231d8bed344 (HEAD)
Author: gingerBill <gingerBill@users.noreply.github.com>
Date:   Mon Sep 29 09:51:23 2025 +0100

    Rearrange const union initialization so that it is priority

 src/llvm_backend.cpp       |   6 --
 src/llvm_backend_const.cpp | 145 +++++++++++----------------------------------
 2 files changed, 35 insertions(+), 116 deletions(-)
```

**Comment by Kelimion** [comment]
I'm going to leave it here for the moment and let @gingerBill pick things up. He's far more familiar with this part of the compiler and the changes he introduced around this area. I would recommend sticking with `dev-2025-08` for the time being, `dev-2025-09` may work as well, as this was introduced at the end of the month.

**Comment by salfel** [comment]
found the place of origin of the error. It happens when assigning nil to a union. 



src/css/lexer.odin:24
```odin
Token :: struct {
	type:  Token_Type,
	value: union {
		string,
		f32,
	},
}
```


src/css/lexer.odin:05
```odin
	append(&token_stream.tokens, Token{.Dot, nil})
```

when changing this to a 0, it works as expected. I don't know if that is expected behaviour, couldn't find any documentation for this specific case.

**Comment by Kelimion** [comment]
Glad you found it. That means you can go back to the latest compiler with this small workaround.

An internal compiler error is never expected behavior. If the odin code leading to the bug is invalid, you should receive a normal compiler error instead of a panic. So this should still be fixed, but I'm happy to know it's not a showstopper for you.
